export { default as LandingPage } from "./LandingPage";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as FAQ } from "./FAQ";
export { default as NavBar } from "./layout/NavBar";
export { default as Footer } from "./layout/Footer";
export { default as Particles } from "./layout/Particles";
export { default as Team } from "./Team";
export { default as Sponsors } from "./Sponsors";
